
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.raincoatmoon.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int AND = 17;
  public static final int RBR = 25;
  public static final int LT = 14;
  public static final int ELSE = 30;
  public static final int PLUS = 3;
  public static final int OR = 18;
  public static final int LP = 22;
  public static final int SEMI = 2;
  public static final int LOOP = 31;
  public static final int RP = 21;
  public static final int NOT = 19;
  public static final int RETURN = 33;
  public static final int IF = 29;
  public static final int GT = 12;
  public static final int ID = 8;
  public static final int LE = 15;
  public static final int ASS = 9;
  public static final int NUM = 16;
  public static final int LB = 24;
  public static final int TYPE = 34;
  public static final int RB = 23;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int THREAD = 28;
  public static final int GE = 13;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int PROC = 32;
  public static final int LBR = 26;
  public static final int EQ = 10;
  public static final int BOOL = 20;
  public static final int NEQ = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "ID",
  "ASS",
  "EQ",
  "NEQ",
  "GT",
  "GE",
  "LT",
  "LE",
  "NUM",
  "AND",
  "OR",
  "NOT",
  "BOOL",
  "RP",
  "LP",
  "RB",
  "LB",
  "RBR",
  "LBR",
  "COMMA",
  "THREAD",
  "IF",
  "ELSE",
  "LOOP",
  "PROC",
  "RETURN",
  "TYPE"
  };
}

